// @lib/types.ts

/**
 * Defines the structure of a WordPress Category node.
 */
export interface Category {
  id: string;
  name: string;
  slug: string;
}

/**
 * Defines the structure of a WordPress Tag node.
 */
export interface Tag {
  id: string;
  name: string;
  slug: string;
}

/**
 * Defines the structure of image data, for a featured image or SEO social image.
 */
export interface MediaItem {
  uri: string;
  sourceUrl: string; // The URL to the image file
  altText: string;
  mediaDetails: {
    height: number;
    width: number;
  };
}

/**
 * Defines the structure for Rank Math SEO data exposed via WPGraphQL (essentials).
 */
export interface SEO {
  title: string;
  metaDesc: string;
  canonical: string;

  fullHead: string; //The complete HTML <head> content string, generated by Rank Math.
  opengraphImage?: {
    sourceUrl: string;
  } | null;
  opengraphTitle: string;
  twitterTitle: string;
}

/**
 * Defines the full structure of a WordPress Post object retrieved via GraphQL.
 */
export interface Post {
  id: string;
  title: string;
  slug: string;
  date: string; // ISO 8601 date string
  excerpt: string;
  content: string; // Raw HTML content

  // Relationships
  categories: {
    nodes: Category[];
  };
  tags: {
    nodes: Tag[];
  };
  featuredImage?: {
    node: MediaItem;
  } | null;

  // Metadata
  seo?: SEO;
}

/**
 * Pagination: Defines the page information object used by cursor-based pagination in WPGraphQL.
 */
export interface PageInfo {
  startCursor: string | null;
  endCursor: string | null;
  hasNextPage: boolean;
  hasPreviousPage: boolean;
}

/**
 * Defines the return structure for the getAllPosts function.
 */
export interface PostListResponse {
  posts: Post[];
  pageInfo: PageInfo;
}
